config/routes.rb
Rails.application.routes.draw do
  # This created all kinds of routes for registration, log in, log out, etc.
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'log_out', sign_up: 'register' }
  # The above changes the following path names to the respective ones (sign_in to login ,etc.) 
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show' # Get the route with /:id and map it to the #show action as portoflio_show
  #, except: [:show] # Bring all of the resource routes except show, so I cna create my own show action
  #get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show' # because otherwise it would still submit it as portfolios
  # Accept get reuest to get /pages/home. This will route to the home action in pages_controller.rb

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'pages/hello'

  get 'tech-news', to: 'pages#tech_news' 


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home' # Setting the homepage as pages/home5
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_name :string
#  slug        :string
#  status      :integer          default("draft")
#  topic_id    :integer
#

class Blog < ApplicationRecord
  validates_presence_of :title, :body

  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status] # Without using the before_action method, we would have to include the code present in set_blog method in each one of the spots in the array.
  # So whenever we have identical code, it's best to put it in a method and use it in a before_action method such as above.
  access all: [:show, :index], user: {except: [:toggle_status, :destroy, :new, :create, :edit, :update]}, site_admin: :all
  layout "blog"
  # GET /blogs
  # GET /blogs.json
  #Whenever we go to localhost:3000/blogs, this index action is what is referenced.
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "Blog Section"
    #@blogs = Blog.limit(1) would only show us Blog #1 or localhos,t:3000/blogs/1
  end

  # GET /blogs/1
  # GET /blogs/1.json
  # This is going to show the particular blog post that we'd click on.
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  # This creates a new instance of the blog, not an entirely new blog.
  # So this would make Blog blog = new Blog() with empty parameters, where the create action will fill in the parameters (title and body)
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
    # Just like new and create, edit is connected to update.
  end

  # POST /blogs
  # POST /blogs.json
  def create
    # Unlike the new action, create takes the formal parameters we typed in "title" and "body".
    # This is why when clicking "New" it leads us to the "New Blog" page without actually creating a new blog, rather a new instance.
    # Once we fill the parameters and hit "Create", the create method will be called which will take the parameters we entered
    # using (blog_params) and will perform validation logic (respond_to).
    @blog = Blog.new(blog_params)
 
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status

    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # This is more of a variable that tells any method using blog_params that this variable fetches :title and :body
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">

  
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta"><%= distance_of_time_in_words(blog.created_at, Time.now) + " ago" %></p>
  <p class="blog-post-meta"><%= link_to blog.status, toggle_status_blog_path(blog) if logged_in?(:site_admin) %></p> 
  
  <p><%= blog.body %></p>
  <p class="blog-post-meta">  
  <%= link_to blog.status, toggle_status_blog_path(blog) if logged_in?(:site_admin) %> |
  <%= link_to 'Edit', edit_blog_path(blog) if logged_in?(:site_admin)%> |
  <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  </p>
  
</div>

app/views/blogs/_form.html.erb
<!--<%= form_tag(blogs_path) do%>
  <div class="form-group">
    <%= label_tag 'blog[title]' %>
    <%= text_field_tag 'blog[title]', nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag 'blog[subtitle]' %>
    <%= text_field_tag 'blog[subtitle]', nil, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag 'blod[body]' %>
    <%= text_area_tag 'blog[body]', nil, class: 'form-control' %> <!-- We need to use blog[x] because rails will expect a hash form in the case of form_tag
    Also, instead of editing, form_tag will create a new instance because it has the method post instead of put. To this reason, form_tag is not used here, rather form_for. form_tags wowuld be used for applications like search engines and any other application that does not require saving/editing, etc.  
  </div>

  <div class="form-group">
    <%= submit_tag 'Save', class: 'btn btn-primary' %>
    <%= text_field_tag 'title', nil, class: 'form-control' %>
  </div> 

  <% end %> -->


 <%= form_with(model: blog, local: true) do |form| %>
   <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %> <!-- If there are any errors, do everythng in this block for as many errors as possibl -->
      <%= alert_generator error %>
   <% end %>
 <% end %>

   <div class="form-group">
     <!-- <%= form.label :title %> -->
     <%= form.text_field :title, class: 'form-control', placeholder: 'Title' %>
   </div>

   <div class="form-group">
     <!-- <%= form.label :body %> -->
     <%= form.text_area :body, class: 'form-control', rows: 40, placeholder: 'Body' %>
   </div>

   <div class="form-group">
     <%= form.submit "Create", class: 'btn btn-primary' %>
   </div>
 <% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

<%= render @blogs %>
<%= paginate @blogs %>
</div><!-- /.blog-main -->

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

<h2><%= @blog.title %></h2>
<%= link_to 'Edit', edit_blog_path(@blog) if logged_in? (:site_admin)%> 
<p> <%= @blog.body %></p>



<%= link_to 'Back', blogs_path %>