config/routes.rb
Rails.application.routes.draw do
  # This created all kinds of routes for registration, log in, log out, etc.
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'log_out', sign_up: 'register' }
  # The above changes the following path names to the respective ones (sign_in to login ,etc.) 
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show' # Get the route with /:id and map it to the #show action as portoflio_show
  #, except: [:show] # Bring all of the resource routes except show, so I cna create my own show action
  #get 'portfolios/:id', to: 'portfolios#show', as: 'portfolio_show' # because otherwise it would still submit it as portfolios
  # Accept get reuest to get /pages/home. This will route to the home action in pages_controller.rb

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

  get 'pages/hello'

  get 'tech-news', to: 'pages#tech_news' 


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home' # Setting the homepage as pages/home5
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id          :integer          not null, primary key
#  title       :string
#  subtitle    :string
#  body        :text
#  main_image  :text
#  thumb_image :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  position    :integer
#

class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,  # Makes destroying a technology possible
                                reject_if: lambda { |attrs| attrs['name'].blank? } # Makes it impossible to add an empty "name" field
  include Placeholder
  validates_presence_of :title, :body, :main_image, :thumb_image

  #mount_uploader :thumb_image, PortfolioUploader
  #mount_uploader :main_image, PortfolioUploader


  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_iems, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all

  def index
    #@portfolio_items = Portfolio.all # Call the model whch is inside the controller and make it available to the view
  @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:poisition])
    end
      render nothing: true
  end

  def new
    @portfolio_item = Portfolio.new
 #   3.times { @portfolio_item.technologies.build }
 
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
 
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to @portfolio_item, notice: 'Portfolio Item is now live' }      
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update

    respond_to do |format|

      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The record was successfully updated' }
      else
        format.html { render :edit }
      end
    end
  end
  
  def show
  end

  def destroy

    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was removed' } 
    end
  end

  private
  def portfolio_params
    params.require(:portfolio).permit( :title, 
                                       :subtitle, 
                                       :body,
                                       technologies_attributes: [:id, :name, :_destroy]
                                       )
  end

 def set_portfolio_item
 @portfolio_item = Portfolio.find(params[:id])
 end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.erorrs.full_messages.each do |error| %> <!-- If there are any errors, do everythng in this block for as many errors as possibl -->
      <%= alert_generator error %>
    <% end %>
   <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 20 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
       <%= render 'technology_fields', f: technology_form %>
      <% end %>
      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>  <!-- Cocoon method that adds a link to add new tech -->
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<% portfolio_item.id %>">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p class="card-text">
    <span><%=link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span>
    <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %> <!--This is linked to the allow_destroy :true in the model as well as the :_destroy in params in the controller. -->
</div>

<!-- nested-fields in the class name is also required for the destroy task to work according tto the cooon documentation -->

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
  <div class="col-md-12">
    <div>

</div>

app/views/portfolios/index.html.erb
<!--><%= render template: "layouts/application" %> -->
<div class="album text-muted">
  <div class="container">
    <div class="row">
      <div class="row sortable">
<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>
<%= render partial: 'portfolio_item', collection: @portfolio_items %>
<!-- The reason why we wrote this render above instead of simply writing render @portfolio item is as follows:
  When rendering partials and we create the partial class, rails is going to expect that the class name is going
  to be the same as that of the model, being Portfolio. So since we have the model name as Portfolio, rails expects
  that its partial is supposed to be called _portfolios, without taking into account that our collection is 
  portfolio_items instead of portfolios, to that reason we have to inform rails that our collection has a different
  name than what it is expecting -->
      </div>
    </div>
  </div>  
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Test</h1>
  <%= form_for(@portfolio_item) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title%>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle%>
    </div>

    <div class="field">Body
      <%= form.label :body %>
      <%= form.text_area :body%>
    </div>

    <ul>
      <%= form.fields_for :technologies do |technology_form| %> <!--This is for the technologies attribute-->
      <li>
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name %>
      </li>
      <% end %>
    </ul>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag @portfolio_item.main_image %>
    </div>

    <div class="col-md-5">

      <h1><%= @portfolio_item.title %></h1>

      <hr>


      <em><%= @portfolio_item.subtitle %></em>
      <p><%= @portfolio_item.body %></p>

      >
      <h2> Tech used: </h2>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
    </div>
    <% if logged_in?(:site_admin) %>
      <div class="col-md-12">
        <%= link_to "Edit", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
      </div>
    <% end %>      
  </div>
</div>